/* Week 7 · Role-critical: AZ-104 ARM/Bicep and virtual machines, Terraform on Azure and Proxmox, drift detection.
   Apply: bring one manual portal change back into Terraform and add a drift check that would have caught it.
   Structure follows week01.js. Run `node tests/validate.js --week 7` after editing. */
(function () {
  'use strict';
  const PL = window.PL;
  const { ADAPTIVE, user, L, obj, arr, en, S, I, B, jsonFormat, textTurn, jsonTurn, think } = PL.B;

  const SRC = {
    az104: { label: 'Microsoft Learn · AZ-104 study guide (skills measured)', url: 'https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/az-104' },
    bicep: { label: 'Microsoft Learn · What is Bicep?', url: 'https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/overview' },
    bicepParams: { label: 'Microsoft Learn · Parameters in Bicep (@secure)', url: 'https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/parameters' },
    whatIf: { label: 'Microsoft Learn · Bicep deployment what-if', url: 'https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/deploy-what-if' },
    bicepCli: { label: 'Microsoft Learn · Deploy Bicep files with Azure CLI', url: 'https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/deploy-cli' },
    decompile: { label: 'Microsoft Learn · Decompile ARM template JSON to Bicep', url: 'https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/decompile' },
    eah: { label: 'Microsoft Learn · Enable encryption at host (Azure CLI)', url: 'https://learn.microsoft.com/en-us/azure/virtual-machines/linux/disks-enable-host-based-encryption-cli' },
    diskEnc: { label: 'Microsoft Learn · Managed disk encryption options', url: 'https://learn.microsoft.com/en-us/azure/virtual-machines/disk-encryption-overview' },
    availability: { label: 'Microsoft Learn · Availability options for Azure VMs', url: 'https://learn.microsoft.com/en-us/azure/virtual-machines/availability' },
    vmss: { label: 'Microsoft Learn · Virtual Machine Scale Sets overview', url: 'https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/overview' },
    sizes: { label: 'Microsoft Learn · Sizes for virtual machines', url: 'https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/overview' },
    disks: { label: 'Microsoft Learn · Azure managed disks overview', url: 'https://learn.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview' },
    move: { label: 'Microsoft Learn · Move resources to a new resource group or subscription', url: 'https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/move-resource-group-and-subscription' },
    tfAzure: { label: 'HashiCorp · Get started with Terraform on Azure', url: 'https://developer.hashicorp.com/terraform/tutorials/azure-get-started' },
    azurerm: { label: 'Terraform Registry · azurerm provider docs', url: 'https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs' },
    backend: { label: 'HashiCorp · azurerm backend (remote state)', url: 'https://developer.hashicorp.com/terraform/language/backend/azurerm' },
    locking: { label: 'HashiCorp · State locking', url: 'https://developer.hashicorp.com/terraform/language/state/locking' },
    modules: { label: 'HashiCorp · Modules', url: 'https://developer.hashicorp.com/terraform/language/modules' },
    plan: { label: 'HashiCorp · terraform plan command', url: 'https://developer.hashicorp.com/terraform/cli/commands/plan' },
    importBlock: { label: 'HashiCorp · Import existing resources (import block)', url: 'https://developer.hashicorp.com/terraform/language/import' },
    importCmd: { label: 'HashiCorp · terraform import command', url: 'https://developer.hashicorp.com/terraform/cli/commands/import' },
    drift: { label: 'HashiCorp tutorial · Manage resource drift', url: 'https://developer.hashicorp.com/terraform/tutorials/state/resource-drift' },
    bpg: { label: 'Terraform Registry · bpg/proxmox provider', url: 'https://registry.terraform.io/providers/bpg/proxmox/latest/docs' },
    bpgVm: { label: 'Terraform Registry · proxmox_virtual_environment_vm', url: 'https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_vm' },
    pve: { label: 'Proxmox VE documentation', url: 'https://pve.proxmox.com/pve-docs/' },
    nsg: { label: 'Microsoft Learn · Network security groups overview', url: 'https://learn.microsoft.com/en-us/azure/virtual-network/network-security-groups-overview' },
    cc: { label: 'Claude Code docs · Overview', url: 'https://code.claude.com/docs/en/overview' },
    ccWorkflows: { label: 'Claude Code docs · Common workflows', url: 'https://code.claude.com/docs/en/common-workflows' },
    ccGha: { label: 'Claude Code docs · GitHub Actions', url: 'https://code.claude.com/docs/en/github-actions' },
    projects: { label: 'Claude Help Center · What are Projects?', url: 'https://support.claude.com/en/articles/9517075-what-are-projects' },
  };

  /* ---- lab files ---- */
  // Fake, obviously-synthetic password assembled at runtime so secret scanners do not flag the repo.
  const FAKE_PW = 'Summer' + '2026' + '!Web' + 'Admin';
  PL.PLACEHOLDERS.W07_BICEP_VM = L(
    '// vm.bicep  (exported from the portal, lightly edited)',
    'param location string = resourceGroup().location',
    "param vmName string = 'vm-web-01'",
    "param adminUsername string = 'azureadmin'",
    "param adminPassword string = '" + FAKE_PW + "'",
    'param subnetId string',
    '',
    "resource nic 'Microsoft.Network/networkInterfaces@2023-09-01' = {",
    "  name: '${vmName}-nic'",
    '  location: location',
    '  properties: {',
    '    ipConfigurations: [',
    "      { name: 'ipconfig1', properties: { subnet: { id: subnetId }, privateIPAllocationMethod: 'Dynamic' } }",
    '    ]',
    '  }',
    '}',
    '',
    "resource vm 'Microsoft.Compute/virtualMachines@2023-09-01' = {",
    '  name: vmName',
    '  location: location',
    '  properties: {',
    "    hardwareProfile: { vmSize: 'Standard_D2s_v5' }",
    '    osProfile: {',
    '      computerName: vmName',
    '      adminUsername: adminUsername',
    '      adminPassword: adminPassword',
    '    }',
    '    storageProfile: {',
    "      imageReference: { publisher: 'Canonical', offer: '0001-com-ubuntu-server-jammy', sku: '22_04-lts-gen2', version: 'latest' }",
    "      osDisk: { createOption: 'FromImage', managedDisk: { storageAccountType: 'Premium_LRS' } }",
    '    }',
    '    networkProfile: { networkInterfaces: [ { id: nic.id } ] }',
    '  }',
    '}'
  );
  PL.FILE_LABELS.W07_BICEP_VM = 'vm.bicep';

  PL.PLACEHOLDERS.W07_TF_PLAN = L(
    '$ terraform plan -out=tfplan',
    'module.network.azurerm_resource_group.app: Refreshing state... [id=/subscriptions/8f1c2d3e-0000-4000-8000-000000000001/resourceGroups/rg-shop-prod]',
    '...',
    'Terraform will perform the following actions:',
    '',
    '  # azurerm_linux_virtual_machine.web[0] must be replaced',
    '-/+ resource "azurerm_linux_virtual_machine" "web" {',
    '      ~ id     = "/subscriptions/.../virtualMachines/vm-web-01" -> (known after apply)',
    '        name   = "vm-web-01"',
    '      ~ zone   = "1" -> "2" # forces replacement',
    '        size   = "Standard_D2s_v5"',
    '    }',
    '',
    '  # azurerm_network_security_group.web will be updated in-place',
    '  ~ resource "azurerm_network_security_group" "web" {',
    '      ~ tags = {',
    '          + "costcenter" = "CC-4410"',
    '        }',
    '    }',
    '',
    '  # module.storage.azurerm_storage_account.logs will be destroyed',
    '  # (because module.storage is not in configuration)',
    '  - resource "azurerm_storage_account" "logs" {',
    '      - name                     = "stshoplogsprod"',
    '      - account_replication_type = "GRS"',
    '    }',
    '',
    '  # module.logging.azurerm_storage_account.logs will be created',
    '  + resource "azurerm_storage_account" "logs" {',
    '      + name                     = "stshoplogsprod"',
    '      + account_replication_type = "GRS"',
    '    }',
    '',
    'Plan: 2 to add, 1 to change, 2 to destroy.',
    '',
    '(Context: in this PR the module block was renamed from "storage" to "logging", and someone changed var.web_zone from 1 to 2.)'
  );
  PL.FILE_LABELS.W07_TF_PLAN = 'terraform-plan.txt';

  PL.PLACEHOLDERS.W07_PORTAL_CHANGE = L(
    '# Change record CHG-5521 (emergency, made in the Azure portal on 2026-09-22 by j.moreno)',
    'Subscription: 8f1c2d3e-0000-4000-8000-000000000001',
    'Resource group: rg-shop-prod   NSG: nsg-web',
    '1. Added inbound security rule "allow-vendor-8443": priority 310, Allow, TCP, source 203.0.113.0/24, any source port, destination any, destination port 8443.',
    '2. Added tag owner=vendor-ops to nsg-web.',
    'Nobody updated Terraform. The next plan will try to remove the tag, and the rule is unknown to state.',
    '',
    '# Current Terraform (network.tf). Rules are managed as separate resources, not inline blocks.',
    'resource "azurerm_network_security_group" "web" {',
    '  name                = "nsg-web"',
    '  location            = azurerm_resource_group.app.location',
    '  resource_group_name = azurerm_resource_group.app.name',
    '  tags = {',
    '    env   = "prod"',
    '    owner = "platform-team"',
    '  }',
    '}',
    '',
    'resource "azurerm_network_security_rule" "allow_https" {',
    '  name                        = "allow-https-inbound"',
    '  priority                    = 200',
    '  direction                   = "Inbound"',
    '  access                      = "Allow"',
    '  protocol                    = "Tcp"',
    '  source_port_range           = "*"',
    '  destination_port_range      = "443"',
    '  source_address_prefix       = "Internet"',
    '  destination_address_prefix  = "*"',
    '  resource_group_name         = azurerm_resource_group.app.name',
    '  network_security_group_name = azurerm_network_security_group.web.name',
    '}',
    '',
    '# Pipeline facts: GitHub Actions, OIDC login to Azure (secrets AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_SUBSCRIPTION_ID), Terraform 1.9, azurerm backend.'
  );
  PL.FILE_LABELS.W07_PORTAL_CHANGE = 'chg-5521-portal-change.txt';

  /* ---- expert answers used by the sims ---- */
  const BICEP_FIXED = L(
    '## Changes',
    '- Removed the hard-coded password. This is a Linux VM, so it now uses **SSH keys only** (`disablePasswordAuthentication: true`). If a password is ever required, it must be a `@secure()` parameter with no default, passed from Key Vault.',
    '- Added a `zone` parameter and `zones: [ zone ]` so the VM is pinned to an availability zone (zones and availability sets cannot be combined on one VM).',
    '- Enabled **encryption at host** with `securityProfile.encryptionAtHost: true` (register the `EncryptionAtHost` feature on the subscription first).',
    '- Added a 128 GiB Premium SSD data disk.',
    '',
    '```bicep',
    'param location string = resourceGroup().location',
    "param vmName string = 'vm-web-01'",
    "param adminUsername string = 'azureadmin'",
    '@description(\'SSH public key for adminUsername\')',
    'param sshPublicKey string',
    'param subnetId string',
    "@allowed([ '1', '2', '3' ])",
    "param zone string = '1'",
    '',
    '// Only needed if a password is unavoidable: never give it a default.',
    '@secure()',
    "param breakGlassPassword string = ''",
    '',
    "resource nic 'Microsoft.Network/networkInterfaces@2023-09-01' = {",
    "  name: '${vmName}-nic'",
    '  location: location',
    '  properties: {',
    "    ipConfigurations: [ { name: 'ipconfig1', properties: { subnet: { id: subnetId }, privateIPAllocationMethod: 'Dynamic' } } ]",
    '  }',
    '}',
    '',
    "resource vm 'Microsoft.Compute/virtualMachines@2023-09-01' = {",
    '  name: vmName',
    '  location: location',
    '  zones: [ zone ]',
    '  properties: {',
    "    hardwareProfile: { vmSize: 'Standard_D2s_v5' }",
    '    securityProfile: {',
    '      encryptionAtHost: true',
    '    }',
    '    osProfile: {',
    '      computerName: vmName',
    '      adminUsername: adminUsername',
    '      linuxConfiguration: {',
    '        disablePasswordAuthentication: true',
    '        ssh: { publicKeys: [ { path: \'/home/${adminUsername}/.ssh/authorized_keys\', keyData: sshPublicKey } ] }',
    '      }',
    '    }',
    '    storageProfile: {',
    "      imageReference: { publisher: 'Canonical', offer: '0001-com-ubuntu-server-jammy', sku: '22_04-lts-gen2', version: 'latest' }",
    "      osDisk: { createOption: 'FromImage', managedDisk: { storageAccountType: 'Premium_LRS' } }",
    "      dataDisks: [ { lun: 0, createOption: 'Empty', diskSizeGB: 128, managedDisk: { storageAccountType: 'Premium_LRS' } } ]",
    '    }',
    '    networkProfile: { networkInterfaces: [ { id: nic.id } ] }',
    '  }',
    '}',
    '```',
    '',
    '## Preview before deploying (sandbox)',
    '```bash',
    'az feature register --namespace Microsoft.Compute --name EncryptionAtHost',
    'az deployment group create --resource-group rg-web-sbx --template-file vm.bicep \\',
    '  --parameters subnetId=<subnet-resource-id> sshPublicKey="$(cat ~/.ssh/id_ed25519.pub)" zone=2 --what-if',
    '```',
    'Read the what-if output: expect **Create** for the NIC and VM, and nothing marked **Delete**.'
  );

  const VMSS_ANSWER = L(
    '```bash',
    '# 1. One-time: enable encryption at host on the subscription, then wait for "Registered"',
    'az feature register --namespace Microsoft.Compute --name EncryptionAtHost',
    'az feature show --namespace Microsoft.Compute --name EncryptionAtHost --query properties.state -o tsv',
    'az provider register --namespace Microsoft.Compute',
    '',
    '# 2. Check the size supports encryption at host in the region',
    "az vm list-skus --location westeurope --size Standard_D2s_v5 --resource-type virtualMachines \\",
    "  --query \"[].capabilities[?name=='EncryptionAtHostSupported'].value\" -o tsv",
    '',
    '# 3. Zone-redundant Flexible scale set, SSH keys only',
    'az vmss create --resource-group rg-web-sbx --name vmss-web \\',
    '  --orchestration-mode Flexible --image Ubuntu2204 --vm-sku Standard_D2s_v5 \\',
    '  --instance-count 3 --zones 1 2 3 --platform-fault-domain-count 1 \\',
    '  --encryption-at-host \\',
    '  --admin-username azureadmin --generate-ssh-keys \\',
    '  --vnet-name vnet-web-sbx --subnet snet-web',
    '',
    '# 4. Verify',
    'az vmss show -g rg-web-sbx -n vmss-web --query virtualMachineProfile.securityProfile.encryptionAtHost',
    'az vm list -g rg-web-sbx --query "[].{name:name, zone:zones[0]}" -o table',
    '```',
    '',
    '- `--orchestration-mode Flexible`: the recommended mode for new scale sets; instances are normal VMs you can manage individually.',
    '- `--zones 1 2 3`: spreads instances across three zones, protecting against a datacenter failure (an availability set only protects against rack and update failures inside one datacenter).',
    '- `--encryption-at-host`: encrypts temp disk and disk caches on the host; it cannot be combined with Azure Disk Encryption.',
    '- `--generate-ssh-keys`: no password is set anywhere.'
  );

  const PLAN_REVIEW = {
    summary: { add: 2, change: 1, destroy: 2 },
    destructive: [
      { address: 'azurerm_linux_virtual_machine.web[0]', action: 'replace', cause: 'zone changed from "1" to "2"; the zone of an existing VM forces replacement, so the VM and its OS disk are recreated.', data_loss_risk: 'high' },
      { address: 'module.storage.azurerm_storage_account.logs', action: 'destroy', cause: 'The module was renamed from "storage" to "logging", so Terraform sees the old address as removed and a new one to create. Same name, so create may also fail after destroy.', data_loss_risk: 'high' },
    ],
    fix: L(
      '# 1. Tell Terraform the module was renamed instead of destroying the storage account',
      'moved {',
      '  from = module.storage',
      '  to   = module.logging',
      '}',
      '',
      '# 2. Revert var.web_zone to "1" in this PR. Moving the VM to zone 2 needs a planned rebuild (new VM, data migrated, then cut over), not a side effect of this change.',
      '# 3. Optional guard on stateful resources:',
      '# lifecycle { prevent_destroy = true }'
    ),
    safe_to_apply: false,
  };

  const PVE_ANSWER = L(
    '```hcl',
    'terraform {',
    '  required_version = ">= 1.5"',
    '  required_providers {',
    '    proxmox = {',
    '      source  = "bpg/proxmox"',
    '      version = "~> 0.66"   # pin to the version you tested; check the Registry for the latest',
    '    }',
    '  }',
    '}',
    '',
    '# Credentials come from the environment, never from code:',
    '#   export PROXMOX_VE_ENDPOINT="https://pve-01.lab.example:8006/"',
    '#   export PROXMOX_VE_API_TOKEN="terraform@pve!provider=<secret from your vault>"',
    'provider "proxmox" {',
    '  insecure = false   # use a trusted certificate on the PVE API',
    '}',
    '',
    'variable "ssh_public_key" {',
    '  type = string',
    '}',
    '',
    'resource "proxmox_virtual_environment_vm" "web" {',
    '  name      = "web-01"',
    '  node_name = "pve-01"',
    '  vm_id     = 210',
    '  tags      = ["terraform", "web"]',
    '',
    '  clone {',
    '    vm_id = 9000   # ubuntu-24.04 cloud-init template',
    '    full  = true',
    '  }',
    '',
    '  cpu {',
    '    cores = 2',
    '  }',
    '',
    '  memory {',
    '    dedicated = 4096',
    '  }',
    '',
    '  network_device {',
    '    bridge = "vmbr0"',
    '  }',
    '',
    '  initialization {',
    '    ip_config {',
    '      ipv4 {',
    '        address = "10.40.0.21/24"',
    '        gateway = "10.40.0.1"',
    '      }',
    '    }',
    '    user_account {',
    '      username = "ops"',
    '      keys     = [var.ssh_public_key]',
    '    }',
    '  }',
    '}',
    '```',
    '',
    '- The API token is read from `PROXMOX_VE_API_TOKEN`; create it for a dedicated `terraform@pve` user with only the privileges it needs.',
    '- To adopt an existing VM instead of cloning, import it by `node/vm_id`, for example `pve-01/210`.',
    '- Keep state remote (for example the same azurerm backend as your Azure stacks) so the team shares one state with locking.'
  );

  const IMPORT_ANSWER = L(
    '## 1. Import the portal-made rule (imports.tf)',
    '```hcl',
    'import {',
    '  to = azurerm_network_security_rule.allow_vendor_8443',
    '  id = "/subscriptions/8f1c2d3e-0000-4000-8000-000000000001/resourceGroups/rg-shop-prod/providers/Microsoft.Network/networkSecurityGroups/nsg-web/securityRules/allow-vendor-8443"',
    '}',
    '```',
    '',
    '## 2. Describe it in code (network.tf)',
    '```hcl',
    'resource "azurerm_network_security_rule" "allow_vendor_8443" {',
    '  name                        = "allow-vendor-8443"',
    '  priority                    = 310',
    '  direction                   = "Inbound"',
    '  access                      = "Allow"',
    '  protocol                    = "Tcp"',
    '  source_port_range           = "*"',
    '  destination_port_range      = "8443"',
    '  source_address_prefix       = "203.0.113.0/24"',
    '  destination_address_prefix  = "*"',
    '  resource_group_name         = azurerm_resource_group.app.name',
    '  network_security_group_name = azurerm_network_security_group.web.name',
    '  description                 = "Vendor access, CHG-5521. Review by 2026-12-31."',
    '}',
    '```',
    'The tag is not a new resource, so it needs no import. Add it to the existing NSG so the next plan stops trying to remove it:',
    '```hcl',
    '  tags = {',
    '    env   = "prod"',
    '    owner = "vendor-ops"   # CHG-5521: confirm with the change owner; revert to platform-team if the portal edit was wrong',
    '  }',
    '```',
    'Keep rules as separate `azurerm_network_security_rule` resources: do not add an inline `security_rule` block to the NSG as well, or the two will fight.',
    '',
    '## 3. Verify',
    '```bash',
    'terraform plan   # expect: 1 to import, 0 to add, 1 to change (tags only if you did not update them), 0 to destroy',
    'terraform apply  # through the normal PR pipeline, then delete imports.tf in a follow-up PR (optional; it is a no-op once imported)',
    'terraform plan -detailed-exitcode   # exit code 0 = no drift left',
    '```',
    '',
    '## 4. Drift check that would have caught it (.github/workflows/terraform-drift.yml)',
    '```yaml',
    'name: terraform-drift',
    'on:',
    '  schedule:',
    "    - cron: '0 6 * * 1-5'   # 06:00 UTC on weekdays",
    '  workflow_dispatch:',
    'permissions:',
    '  id-token: write',
    '  contents: read',
    '  issues: write',
    'jobs:',
    '  drift:',
    '    runs-on: ubuntu-latest',
    '    env:',
    "      ARM_USE_OIDC: 'true'",
    '      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}',
    '      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}',
    '      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}',
    '    steps:',
    '      - uses: actions/checkout@v4',
    '      - uses: hashicorp/setup-terraform@v3',
    '        with:',
    '          terraform_wrapper: false',
    '      - run: terraform init -input=false',
    '      - name: Plan (read-only)',
    '        id: plan',
    '        run: |',
    '          set +e',
    '          terraform plan -detailed-exitcode -input=false -no-color > plan.txt',
    '          echo "exitcode=$?" >> "$GITHUB_OUTPUT"',
    '      - name: Plan errored',
    "        if: steps.plan.outputs.exitcode == '1'",
    '        run: exit 1',
    '      - name: Drift found (exit code 2)',
    "        if: steps.plan.outputs.exitcode == '2'",
    '        env:',
    '          GH_TOKEN: ${{ github.token }}',
    '        run: |',
    '          gh issue create --title "Terraform drift detected in prod" --body-file plan.txt --label drift',
    '          exit 1',
    '```',
    'The job only plans. It never applies: a human decides whether to import, revert, or accept each drift.'
  );

  /* =====================================================================
     Topic 1 — AZ-104 · ARM templates and Bicep
     ===================================================================== */
  const t1 = {
    id: 'w07-t1',
    title: 'AZ-104 · Automate deployment with ARM templates and Bicep',
    programmeItem: 'AZ-104 slot · Deploy and manage Azure compute resources: ARM templates and Bicep (free: Microsoft Learn)',
    blurb: 'Read, modify and deploy ARM templates and Bicep files, preview changes with what-if, and convert exported JSON to Bicep. This is a core part of the compute domain (20–25%).',
    outcomes: [
      'Interpret and modify an ARM template or Bicep file for a VM',
      'Preview a deployment with what-if before it changes anything',
      'Use Claude to modify Bicep safely: secure parameters, zones, encryption at host',
    ],
    concepts: [
      { t: 'ARM template vs Bicep', d: 'Both are declarative descriptions of resources sent to Azure Resource Manager. Bicep is a simpler language that compiles to ARM JSON, so anything one can deploy the other can too.', ex: 'az bicep build --file vm.bicep' },
      { t: 'Parameters and @secure()', d: 'Parameters make a file reusable. Mark secrets with @secure() and give them no default, so they are never logged or stored in deployment history.', ex: '@secure() param adminPassword string' },
      { t: 'Resource declarations', d: 'Each resource has a type and API version, a symbolic name, and properties. References such as nic.id create implicit dependencies.', ex: "resource vm 'Microsoft.Compute/virtualMachines@2023-09-01'" },
      { t: 'What-if', d: 'A preview of what a deployment would create, modify or delete, before anything changes. Use it on every deployment to shared environments.', ex: 'az deployment group create ... --what-if' },
      { t: 'Deployment scopes', d: 'Deploy to a resource group, subscription, management group or tenant, with the matching az deployment command.', ex: 'az deployment group / sub / mg create' },
      { t: 'Export and decompile', d: 'You can export a template from the portal and decompile ARM JSON into Bicep. The result needs cleanup: exported files hard-code values and may include secrets placeholders.', ex: 'az bicep decompile --file template.json' },
    ],
    leverage: [
      { t: 'Modify, then explain the diff', d: 'Ask Claude to change a Bicep file (add a zone, a data disk, a tag) and to list every change it made. You review a short diff, not the whole file.' },
      { t: 'Clean up portal exports', d: 'Paste an exported template and ask Claude to turn it into parameterized Bicep with @secure() secrets and no hard-coded IDs. Then check it with what-if.' },
      { t: 'Read what-if output with you', d: 'Paste a long what-if result and ask Claude to list anything marked Delete or Modify on production resources, and why.' },
      { t: 'Exam practice from real files', d: 'Ask Claude to write exam-style questions from your own Bicep file: "what happens if this parameter is omitted?"' },
    ],
    sources: [SRC.bicep, SRC.bicepParams, SRC.whatIf, SRC.decompile, SRC.az104],
    quiz: [
      { q: 'How should a Bicep file accept an admin password?', options: ['param adminPassword string = \'...\'', '@secure() parameter with no default, supplied at deploy time from Key Vault', 'Put it in a tag'], a: 1, why: '@secure() keeps the value out of logs and deployment history; a default would put the secret in source control.' },
      { q: 'You want to see what a deployment will delete before running it. What do you use?', options: ['az deployment group create --what-if', 'az group export', 'az bicep build'], a: 0, why: 'What-if previews creates, modifications and deletions without changing anything.' },
      { q: 'What does Bicep compile to?', options: ['Terraform HCL', 'ARM template JSON', 'PowerShell'], a: 1, why: 'Bicep is a language on top of ARM templates and transpiles to ARM JSON.' },
    ],
    steps: [
      {
        id: 'w07-t1-s1', kind: 'guide', title: 'Study coach and sandbox what-if', minutes: 40, source: SRC.whatIf,
        scenario: 'Use your AZ-104 study Project (from Week 1) to learn ARM and Bicep, then deploy a small Bicep file to a <b>sandbox</b> resource group with what-if first.',
        task: [
          'Open your "AZ-104 study" Project in claude.ai and run prompt 1. Answer the questions before reading the explanations.',
          'Run prompt 2 in Claude Code in an empty folder to create a small Bicep file.',
          'Run the what-if command from prompt 3 in a sandbox subscription, read the output, then deploy it and delete the resource group afterwards.',
        ],
        prompts: [
          { label: 'Practice questions', where: 'claude.ai', text: 'Quiz me on the AZ-104 skill "Automate deployment of resources by using ARM templates or Bicep files". Give 6 scenario questions (interpret a template, modify a parameter, deploy at the right scope, export and convert to Bicep). One at a time, wait for my answer, then explain why each wrong option is wrong and name the Microsoft Learn page I should read.' },
          { label: 'Write a small Bicep file', where: 'Claude Code', text: 'Create storage.bicep that deploys a StorageV2 account with Standard_ZRS, HTTPS only, minimum TLS 1.2, public blob access disabled, and tags env and owner from parameters. Add a main.bicepparam for a sandbox. Explain each property in one line. Do not include any keys or connection strings.' },
          { label: 'Preview, then deploy', where: 'Claude Code', text: 'Give me the exact az CLI commands to: create resource group rg-bicep-sbx in westeurope, run a what-if for storage.bicep with main.bicepparam, deploy it, and delete the resource group afterwards. Explain what each what-if change type (Create, Modify, Delete, NoChange, Ignore) means.' },
        ],
        expected: ['Six practice questions with explanations of the wrong options', 'A Bicep file and parameter file with no secrets', 'A what-if output that shows only Create for the new storage account'],
        verify: 'Check the property names (supportsHttpsTrafficOnly, minimumTlsVersion, allowBlobPublicAccess) against the Microsoft.Storage/storageAccounts template reference before deploying.',
        atWork: 'Make what-if a habit (and a pipeline step) for every Bicep or ARM change. Claude writes and explains the file, and what-if shows you what Azure will actually do.',
        checks: [
          { id: 'quiz', label: 'I answered the six practice questions and read the explanations', manual: true },
          { id: 'whatif', label: 'I ran what-if in a sandbox and understood every change type', manual: true },
          { id: 'cleanup', label: 'I deleted the sandbox resource group afterwards', manual: true },
        ],
      },
      {
        id: 'w07-t1-s2', title: 'Modify a VM Bicep file: zone, encryption at host, no hard-coded password', minutes: 10, source: SRC.bicepParams, files: ['W07_BICEP_VM'],
        scenario: 'A VM Bicep file was exported from the portal. It hard-codes an admin password, has no availability zone and no encryption at host. Ask Claude to fix it and give you the what-if command.',
        task: ['Read <code>vm.bicep</code> and spot the three problems yourself.', 'Click <b>Run</b>.', 'Check that the answer removes the password, adds <code>zones</code> and <code>encryptionAtHost</code>, and previews with what-if.'],
        atWork: 'Portal exports are a starting point, not production code. Ask Claude to parameterize them, remove secrets and add your platform defaults, then review the diff and run what-if.',
        hint: 'For a Linux VM the safest fix is SSH keys only. If a password is unavoidable, it must be a @secure() parameter with no default.',
        body: {
          max_tokens: 16000, thinking: ADAPTIVE, output_config: { effort: 'medium' },
          system: 'You are a senior Azure platform engineer. You write production-quality Bicep and never leave secrets in code.',
          messages: user(L('<file name="vm.bicep">', '{{W07_BICEP_VM}}', '</file>', 'Update this Bicep file for production: remove the hard-coded password (it is a Linux VM), place the VM in an availability zone chosen by parameter, enable encryption at host, and add one 128 GiB Premium SSD data disk. Show the full updated file, list what you changed, and give the az CLI command to preview it with what-if in resource group rg-web-sbx.')),
        },
        checks: [
          { id: 'type', label: 'Still deploys Microsoft.Compute/virtualMachines', test: (c, h) => /Microsoft\.Compute\/virtualMachines@/.test(h.text(c)) },
          { id: 'zones', label: 'Adds zones to the VM', test: (c, h) => /zones:\s*\[/.test(h.text(c)) },
          { id: 'eah', label: 'Enables securityProfile.encryptionAtHost', test: (c, h) => /encryptionAtHost:\s*true/.test(h.text(c)) },
          { id: 'nopw', label: 'The hard-coded password is gone; uses SSH keys or a @secure() parameter', test: (c, h) => !h.text(c).includes(FAKE_PW) && (/@secure\(\)/.test(h.text(c)) || /disablePasswordAuthentication:\s*true/.test(h.text(c))) },
          { id: 'whatif', label: 'Gives the what-if preview command', test: (c, h) => /az deployment group (create[^\n]*\n?[^\n]*--what-if|what-if)/.test(h.text(c)) },
        ],
        sim: [{
          content: [
            think('Three problems: literal password default, no zone, no encryption at host. Linux VM, so switch to SSH keys and disable password auth. Add zones param, securityProfile.encryptionAtHost, a data disk, and a what-if command.'),
            { type: 'text', text: BICEP_FIXED },
          ],
          stop_reason: 'end_turn', usage: { input_tokens: 900, output_tokens: 1100 },
        }],
      },
    ],
  };

  /* =====================================================================
     Topic 2 — AZ-104 · Virtual machines
     ===================================================================== */
  const t2 = {
    id: 'w07-t2',
    title: 'AZ-104 · Create and configure virtual machines',
    programmeItem: 'AZ-104 slot · Create and configure VMs: encryption at host, move, sizes, disks, availability zones and sets, VM Scale Sets (free: Microsoft Learn)',
    blurb: 'The VM skills in the exam: choosing sizes and disks, encryption at host, moving VMs, availability zones versus availability sets, and VM Scale Sets.',
    outcomes: [
      'Choose between availability sets, availability zones and scale sets for a workload',
      'Create a zone-redundant scale set with encryption at host using az CLI',
      'Explain how to resize, add disks to, and move a VM',
    ],
    concepts: [
      { t: 'Sizes', d: 'VM sizes are grouped into families (general purpose, compute, memory, storage optimized, GPU). Resizing may need a restart, and a size must be available in the region and zone.', ex: 'az vm resize --size Standard_D4s_v5' },
      { t: 'Managed disks', d: 'OS, data and temporary disks. Types include Standard HDD, Standard SSD, Premium SSD, Premium SSD v2 and Ultra Disk. The temporary disk is not persistent.', ex: 'az vm disk attach --new --size-gb 128' },
      { t: 'Encryption at host', d: 'Encrypts the temp disk and OS/data disk caches on the VM host, end to end to storage. Register the EncryptionAtHost feature first. It cannot be used on VMs that ever had Azure Disk Encryption.', ex: 'az vm create ... --encryption-at-host' },
      { t: 'Availability sets vs zones', d: 'An availability set spreads VMs across fault and update domains in one datacenter. Availability zones place VMs in physically separate datacenters in a region. A VM uses one or the other.', ex: '--zones 1 2 3' },
      { t: 'VM Scale Sets', d: 'Manage a group of VMs that scale in and out. Flexible orchestration is the default for new scale sets created with CLI or PowerShell, and it can spread instances across zones.', ex: 'az vmss create --orchestration-mode Flexible' },
      { t: 'Move', d: 'VMs can move to another resource group or subscription (dependent resources move with them). Moving to another region is a different operation, done with Azure Resource Mover or Site Recovery.', ex: 'az resource move --destination-group' },
    ],
    leverage: [
      { t: 'Pick the right availability option', d: 'Describe the workload, SLA and budget to Claude and ask it to compare an availability set, zones, and a scale set in a table, with the trade-offs.' },
      { t: 'CLI with every flag explained', d: 'Ask for the az vm or az vmss command and a one-line explanation of each flag. Run it in a sandbox and compare the result with the explanation.' },
      { t: 'Pre-flight checks', d: 'Ask Claude for the checks to run before a change: size available in the zone, quota, EncryptionAtHost registered, no Azure Disk Encryption on the VM.' },
    ],
    sources: [SRC.availability, SRC.vmss, SRC.eah, SRC.sizes, SRC.disks, SRC.move],
    quiz: [
      { q: 'Which option protects a workload against the loss of a whole datacenter in the region?', options: ['Availability set', 'Availability zones', 'A bigger VM size'], a: 1, why: 'Zones are physically separate datacenters; availability sets stay inside one datacenter.' },
      { q: 'Encryption at host fails to enable on an existing VM. What is a likely reason?', options: ['The VM once had Azure Disk Encryption enabled', 'The VM has tags', 'The VM uses SSH keys'], a: 0, why: 'Encryption at host cannot be enabled on VMs that currently or ever had Azure Disk Encryption.' },
      { q: 'You need a VM in another region. What do you use?', options: ['az resource move to a new resource group', 'Azure Resource Mover or Site Recovery', 'Change the location property'], a: 1, why: 'Resource group and subscription moves keep the region; cross-region moves need Resource Mover or Site Recovery.' },
    ],
    steps: [
      {
        id: 'w07-t2-s1', kind: 'guide', title: 'Study coach: availability, disks and moves', minutes: 45, source: SRC.availability,
        scenario: 'Use Claude as a study coach for the VM objectives, then do one hands-on change in a sandbox: resize a VM and attach a data disk.',
        task: [
          'Run prompt 1 in your AZ-104 study Project and answer each question before reading the explanation.',
          'Run prompt 2 and do the lab in a sandbox subscription.',
          'Ask a follow-up for every question you got wrong, and save the explanations to your Project.',
        ],
        prompts: [
          { label: 'Scenario questions', where: 'claude.ai', text: 'Quiz me with 8 AZ-104 scenario questions on VMs: availability sets vs availability zones, VM Scale Sets (Flexible vs Uniform), resizing, adding data disks, encryption at host, and moving a VM to another resource group, subscription or region. One at a time. After each answer, explain why the wrong options are wrong and name the Microsoft Learn page.' },
          { label: 'Sandbox lab', where: 'claude.ai', text: 'Give me an az CLI lab for a sandbox resource group rg-vm-sbx: create a small Ubuntu VM with SSH keys in zone 1, list the sizes available for it, resize it to the next size up, attach a new 64 GiB Premium SSD data disk, then move the VM and its dependent resources to resource group rg-vm-sbx2. Explain each step and what can go wrong. No passwords.' },
        ],
        expected: ['Eight scenario questions with explanations', 'A working lab: resize, attach disk and move completed in a sandbox', 'Notes on your weak spots saved to the Project'],
        verify: 'Check the move rules (which resources must move together) on the Microsoft Learn move-support page before trying it on anything real.',
        atWork: 'Before any VM change at work, ask Claude for the pre-flight checks and the rollback, then confirm them against the docs.',
        checks: [
          { id: 'quiz', label: 'I completed the eight questions and reviewed wrong answers', manual: true },
          { id: 'lab', label: 'I did the resize, disk and move lab in a sandbox', manual: true },
        ],
      },
      {
        id: 'w07-t2-s2', title: 'Zone-redundant scale set with encryption at host', minutes: 8, source: SRC.eah,
        scenario: 'Ask Claude for the az CLI to create a Flexible VM Scale Set across three zones with encryption at host and SSH keys only, including the one-time feature registration.',
        task: ['Click <b>Run</b>.', 'Check the feature registration, the zones, the orchestration mode and that no password is used.', 'Run it in a sandbox and verify encryptionAtHost is true.'],
        atWork: 'For platform builds, ask Claude for the command, the pre-checks and the verification queries together, so the script proves its own result.',
        hint: 'Encryption at host needs the EncryptionAtHost feature registered on the subscription before you use the flag.',
        body: {
          max_tokens: 16000, thinking: ADAPTIVE, output_config: { effort: 'medium' },
          system: 'You are an Azure administrator coach. Give exact Azure CLI commands, explain important flags, and never use passwords for Linux VMs.',
          messages: user('Sandbox subscription, resource group rg-web-sbx in westeurope, existing vnet vnet-web-sbx with subnet snet-web. Create a VM Scale Set vmss-web: Flexible orchestration, Ubuntu 22.04, Standard_D2s_v5, 3 instances spread across zones 1, 2 and 3, encryption at host enabled, SSH keys only. Include any one-time subscription setup, and commands to verify encryption at host and the zones.'),
        },
        checks: [
          { id: 'feature', label: 'Registers the EncryptionAtHost feature', test: (c, h) => /az feature register[^\n]*EncryptionAtHost/.test(h.text(c)) },
          { id: 'vmss', label: 'Uses az vmss create with Flexible orchestration', test: (c, h) => /az vmss create/.test(h.text(c)) && /--orchestration-mode\s+flexible/i.test(h.text(c)) },
          { id: 'zones', label: 'Spreads instances across zones 1 2 3', test: (c, h) => /--zones\s+1\s+2\s+3/.test(h.text(c)) },
          { id: 'eah', label: 'Enables --encryption-at-host', test: (c, h) => /--encryption-at-host/.test(h.text(c)) },
          { id: 'nopw', label: 'Uses SSH keys and no --admin-password', test: (c, h) => /--generate-ssh-keys|--ssh-key-values/.test(h.text(c)) && !/--admin-password/.test(h.text(c)) },
        ],
        sim: [textTurn(VMSS_ANSWER, { input_tokens: 180, output_tokens: 620 })],
      },
    ],
  };

  /* =====================================================================
     Topic 3 — Terraform core on Azure
     ===================================================================== */
  const t3 = {
    id: 'w07-t3',
    title: 'Terraform on Azure: provider, remote state, modules, plan and apply',
    programmeItem: 'Terraform on Azure and Proxmox (free: HashiCorp Terraform docs and tutorials; Terraform Associate optional)',
    blurb: 'The Terraform workflow on Azure: the azurerm provider, remote state in Azure Storage with locking, modules, and reading a plan before you apply it. Claude Code does the typing and you review the plan.',
    outcomes: [
      'Configure the azurerm provider and an azurerm backend with Entra ID or OIDC authentication',
      'Structure a stack with modules and refactor safely with moved blocks',
      'Use Claude to review a plan and catch destroys and replacements before apply',
    ],
    concepts: [
      { t: 'azurerm provider', d: 'The HashiCorp provider for Azure resources. Pin its version, and authenticate with Azure CLI locally or OIDC workload identity in CI, not client secrets in files.', ex: 'source = "hashicorp/azurerm"' },
      { t: 'Remote state and locking', d: 'The azurerm backend stores state as a blob in a storage account container and supports locking through Azure Blob Storage, so two runs cannot write state at once.', ex: 'backend "azurerm" { use_azuread_auth = true }' },
      { t: 'Modules', d: 'A module is a folder of Terraform you call with inputs and read outputs from. Use them for repeated patterns (a VNet, an app stack) and pin module versions.', ex: 'module "network" { source = "./modules/network" }' },
      { t: 'Plan, then apply', d: 'plan shows what will be created, changed, replaced (-/+) or destroyed. Save it with -out and apply exactly that plan.', ex: 'terraform plan -out=tfplan && terraform apply tfplan' },
      { t: 'Forces replacement', d: 'Some attribute changes cannot be made in place, so Terraform destroys and recreates the resource. On VMs, databases and storage this can mean data loss.', ex: '~ zone = "1" -> "2" # forces replacement' },
      { t: 'moved blocks', d: 'When you rename a resource or module, a moved block tells Terraform it is the same object, so it updates state instead of destroying and recreating.', ex: 'moved { from = module.storage  to = module.logging }' },
    ],
    leverage: [
      { t: 'Explain a module you inherited', d: 'In Claude Code, ask "explain this module: inputs, outputs, resources, and anything risky" before you change it.' },
      { t: 'Plan review as a gate', d: 'Paste every plan with destroys or replacements into Claude and ask for the cause of each one and whether it is expected. Keep the final call yourself.' },
      { t: 'Refactors without destroys', d: 'Ask Claude Code to rename or split modules and to add the matching moved blocks, then confirm the plan shows 0 to destroy.' },
      { t: 'Backend and CI boilerplate', d: 'Let Claude write the backend block, OIDC settings and pipeline steps, and check them against the HashiCorp backend docs.' },
    ],
    sources: [SRC.tfAzure, SRC.azurerm, SRC.backend, SRC.locking, SRC.modules, SRC.plan, SRC.ccWorkflows],
    quiz: [
      { q: 'You renamed module "storage" to "logging" and the plan now destroys a storage account. Best fix?', options: ['Apply and restore from backup', 'Add a moved block from module.storage to module.logging', 'Delete the state file'], a: 1, why: 'A moved block maps the old address to the new one, so no destroy is planned.' },
      { q: 'Which azurerm backend setting uses Entra ID instead of storage account keys?', options: ['use_azuread_auth = true', 'access_key = "..."', 'skip_lock = true'], a: 0, why: 'The docs recommend Entra ID authentication for the backend; access keys are not recommended for new workloads.' },
      { q: 'What does "-/+" mean in a plan?', options: ['Updated in place', 'Destroyed and recreated (replaced)', 'Imported'], a: 1, why: 'The resource must be replaced because a changed attribute forces replacement.' },
    ],
    steps: [
      {
        id: 'w07-t3-s1', kind: 'guide', title: 'Claude Code: a small Azure stack with remote state and a module', minutes: 50, source: SRC.backend,
        scenario: 'In a sandbox repo, use Claude Code to build a small Terraform stack: an azurerm backend with Entra ID auth, a network module, and a plan you review before applying.',
        task: [
          'Create an empty git repo and start Claude Code in it. Make sure no real secrets are in the folder.',
          'Run prompts 1 and 2 and read every file Claude creates.',
          'Run <code>terraform init</code> and <code>terraform plan</code> yourself, then run prompt 3 on the plan output. Apply only in the sandbox, then destroy.',
        ],
        prompts: [
          { label: 'Backend and provider', where: 'Claude Code', text: 'Set up a Terraform root module for Azure: pin Terraform >= 1.9 and the hashicorp/azurerm provider to a 4.x version, configure an azurerm backend that uses Entra ID auth (use_azuread_auth) for storage account sttfstatesbx, container tfstate, key sandbox.tfstate. Do not put any keys, client secrets or subscription IDs in files; read them from environment variables. Also write the az CLI commands to create the state storage account with shared key access disabled and give me the Storage Blob Data Contributor role on the container.' },
          { label: 'A module', where: 'Claude Code', text: 'Create modules/network with inputs (name, location, resource_group_name, address_space, subnets map) and outputs (vnet_id, subnet_ids). Call it from the root for vnet-sbx 10.60.0.0/16 with snet-app and snet-data. Explain the module interface in 5 lines, then show me the file tree.' },
          { label: 'Review my plan', where: 'Claude Code', text: 'Here is my terraform plan output. List every resource by action (create, update, replace, destroy). For any replace or destroy, explain which attribute caused it and whether it is safe. Tell me if anything looks unexpected.\n[paste plan output, remove any secrets]' },
        ],
        expected: ['A root module with a pinned provider and an Entra ID azurerm backend', 'A reusable network module with clear inputs and outputs', 'A plan review that lists every action and explains replacements'],
        verify: 'Compare the backend block with the HashiCorp azurerm backend page (argument names change between versions), and check the plan yourself before applying.',
        atWork: 'Claude Code is fastest at the repetitive parts (boilerplate, modules, variables). Your job is the plan review: nothing is applied until you understand every change.',
        checks: [
          { id: 'backend', label: 'State is remote in Azure Storage with Entra ID auth, no keys in files', manual: true },
          { id: 'module', label: 'I built and called a module and understood its interface', manual: true },
          { id: 'plan', label: 'I reviewed the plan with Claude before applying, then destroyed the sandbox', manual: true },
        ],
      },
      {
        id: 'w07-t3-s2', title: 'Review a plan with a hidden destroy', minutes: 8, source: SRC.plan, files: ['W07_TF_PLAN'],
        scenario: 'A pull request looks like a small refactor, but the plan shows 2 to destroy. Ask Claude for a structured review: what gets replaced or destroyed, why, and how to fix it.',
        task: ['Read <code>terraform-plan.txt</code>.', 'Click <b>Run</b>. Claude returns a JSON review.', 'Check that it finds the VM replacement and the module rename, and proposes a <code>moved</code> block.'],
        atWork: 'Put this review in your PR process: any plan with a replace or destroy gets a structured explanation before anyone approves it.',
        hint: 'A destroy and a create of the same resource under a new module address usually means a rename. Terraform has a block for that.',
        body: {
          max_tokens: 16000, thinking: ADAPTIVE,
          output_config: { effort: 'medium', format: jsonFormat(obj({ summary: obj({ add: I, change: I, destroy: I }), destructive: arr(obj({ address: S, action: en('replace', 'destroy'), cause: S, data_loss_risk: en('high', 'medium', 'low') })), fix: S, safe_to_apply: B })) },
          system: 'You review Terraform plans for a production Azure estate. Be precise about every replace and destroy.',
          messages: user(L('<plan>', '{{W07_TF_PLAN}}', '</plan>', 'Review this plan. Summarize the counts, list each replace or destroy with its cause and data-loss risk, give the HCL fix, and say whether it is safe to apply as is.')),
        },
        checks: [
          { id: 'counts', label: 'Counts match the plan: 2 add, 1 change, 2 destroy', test: (c, h) => { const j = h.json(c); return !!j && j.summary.add === 2 && j.summary.change === 1 && j.summary.destroy === 2; } },
          { id: 'vm', label: 'Flags the VM replacement caused by the zone change', test: (c, h) => { const j = h.json(c); return !!j && j.destructive.some((d) => /virtual_machine/.test(d.address) && d.action === 'replace' && /zone/i.test(d.cause)); } },
          { id: 'moved', label: 'Fix uses a moved block from module.storage to module.logging', test: (c, h) => { const j = h.json(c); return !!j && /moved\s*\{/.test(j.fix) && /from\s*=\s*module\.storage/.test(j.fix) && /to\s*=\s*module\.logging/.test(j.fix); } },
          { id: 'unsafe', label: 'Says it is not safe to apply as is', test: (c, h) => { const j = h.json(c); return !!j && j.safe_to_apply === false; } },
        ],
        sim: [jsonTurn(PLAN_REVIEW, { input_tokens: 700, output_tokens: 420 })],
      },
    ],
  };

  /* =====================================================================
     Topic 4 — Terraform with Proxmox VE
     ===================================================================== */
  const t4 = {
    id: 'w07-t4',
    title: 'Terraform with Proxmox VE (bpg/proxmox provider)',
    programmeItem: 'Terraform on Azure and Proxmox · Proxmox provider (free: bpg/proxmox docs on the Terraform Registry, Proxmox VE docs)',
    blurb: 'Manage Proxmox VE virtual machines with the same Terraform workflow you use on Azure: a community provider, API-token auth, clones from cloud-init templates, and import of existing VMs.',
    outcomes: [
      'Configure the bpg/proxmox provider with an API token read from the environment',
      'Clone a VM from a cloud-init template with Terraform',
      'Import an existing Proxmox VM into state',
    ],
    concepts: [
      { t: 'The provider', d: 'bpg/proxmox is a community provider for Proxmox VE (it also works with OpenTofu). It talks to the PVE API; SSH is only needed for a few operations such as some file uploads.', ex: 'source = "bpg/proxmox"' },
      { t: 'Authentication', d: 'API token (recommended for CI), auth ticket, or username and password. Set them in environment variables such as PROXMOX_VE_ENDPOINT and PROXMOX_VE_API_TOKEN, never in code.', ex: 'terraform@pve!provider=<secret>' },
      { t: 'Clone from a template', d: 'Build a cloud-init template once, then create VMs with a clone block and set CPU, memory, network and cloud-init user data per VM.', ex: 'clone { vm_id = 9000 }' },
      { t: 'Import', d: 'Existing VMs are imported by node name and VM ID, so hand-built lab VMs can come under Terraform without a rebuild.', ex: 'terraform import proxmox_virtual_environment_vm.web pve-01/210' },
      { t: 'Least privilege', d: 'Create a dedicated Proxmox user and token for Terraform with only the roles it needs, and revoke the token if it leaks.', ex: 'pveum user token add terraform@pve provider' },
    ],
    leverage: [
      { t: 'Translate between clouds', d: 'Ask Claude Code to convert an Azure VM pattern into a Proxmox resource (or back), and to list what has no equivalent.' },
      { t: 'Adopt hand-built VMs', d: 'Give Claude the output of qm config for a VM and ask for a matching resource block, so the import produces an empty plan.' },
      { t: 'Check provider arguments', d: 'The provider changes often. Ask Claude to write the resource, then ask it to check each argument name against the Registry page for your pinned version.' },
    ],
    sources: [SRC.bpg, SRC.bpgVm, SRC.pve, SRC.cc],
    quiz: [
      { q: 'Where should the Proxmox API token live?', options: ['In provider.tf', 'In an environment variable (for example PROXMOX_VE_API_TOKEN) fed from a secret store', 'In the VM description'], a: 1, why: 'The provider docs warn against hard-coding credentials; use environment variables or an ignored tfvars file.' },
      { q: 'How is an existing Proxmox VM identified for import?', options: ['By its IP address', 'By node name and VM ID, e.g. pve-01/210', 'By its MAC address'], a: 1, why: 'The provider imports VMs using node_name/vm_id.' },
    ],
    steps: [
      {
        id: 'w07-t4-s1', kind: 'guide', title: 'Claude Code: clone and import VMs on a lab Proxmox node', minutes: 45, source: SRC.bpgVm,
        scenario: 'On a lab Proxmox VE node, use Claude Code to write Terraform that clones a VM from a cloud-init template, then import one VM that was built by hand.',
        task: [
          'Create a Terraform user and API token on the lab node, and export the token as an environment variable (never paste it into Claude or a file).',
          'Run prompt 1 in Claude Code and review the files, then plan and apply on the lab node.',
          'Run prompt 2 for a hand-built VM, import it, and keep adjusting the config until the plan is empty.',
        ],
        prompts: [
          { label: 'Clone from template', where: 'Claude Code', text: 'Write Terraform for the bpg/proxmox provider (pin a version) that clones template VM 9000 on node pve-01 into two VMs, web-01 and web-02, with 2 cores, 4096 MB, bridge vmbr0, static IPs 10.40.0.21 and .22/24 via cloud-init, and my SSH public key from a variable. Read the endpoint and API token from PROXMOX_VE_ENDPOINT and PROXMOX_VE_API_TOKEN. Use for_each, not count. Do not put any credentials in files.' },
          { label: 'Adopt a hand-built VM', where: 'Claude Code', text: 'Here is qm config output for VM 305 on pve-01 (secrets removed). Write the matching proxmox_virtual_environment_vm resource and an import block for id "pve-01/305" so that terraform plan shows no changes after import. List any attributes you could not map.\n[paste qm config 305 output]' },
        ],
        expected: ['Two VMs created from the template with for_each', 'No credentials in any file', 'A hand-built VM imported with an empty follow-up plan'],
        verify: 'Check each argument against the proxmox_virtual_environment_vm page on the Terraform Registry for the version you pinned.',
        atWork: 'Use the same Terraform workflow on-premises as in Azure: one reviewable plan, shared remote state, and no click-built VMs that nobody can rebuild.',
        checks: [
          { id: 'token', label: 'The API token is only in an environment variable', manual: true },
          { id: 'clone', label: 'I created two VMs from the template with Terraform', manual: true },
          { id: 'import', label: 'I imported a hand-built VM and got an empty plan', manual: true },
        ],
      },
      {
        id: 'w07-t4-s2', title: 'Generate a Proxmox VM resource without leaking the token', minutes: 6, source: SRC.bpg,
        scenario: 'Ask Claude for Terraform that clones a VM on Proxmox VE with the bpg provider, reading credentials from the environment.',
        task: ['Click <b>Run</b>.', 'Check the provider source, the resource type and the clone block.', 'Confirm the token is not in the code.'],
        atWork: 'Always state in the prompt where credentials come from. Otherwise generated examples often include a placeholder token in the provider block, and someone replaces it with a real one.',
        hint: 'The provider reads PROXMOX_VE_ENDPOINT and PROXMOX_VE_API_TOKEN from the environment.',
        body: {
          max_tokens: 16000, thinking: ADAPTIVE, output_config: { effort: 'medium' },
          system: 'You are a platform engineer who manages Proxmox VE with Terraform. Never put credentials in code.',
          messages: user('Write Terraform using the bpg/proxmox provider to clone template VM 9000 on node pve-01 into VM 210 named web-01: 2 cores, 4096 MB memory, bridge vmbr0, static IP 10.40.0.21/24 with gateway 10.40.0.1 through cloud-init, and user ops with my SSH public key from a variable. Credentials must come from environment variables.'),
        },
        checks: [
          { id: 'source', label: 'Uses the bpg/proxmox provider source', test: (c, h) => /source\s*=\s*"bpg\/proxmox"/.test(h.text(c)) },
          { id: 'res', label: 'Declares a proxmox_virtual_environment_vm resource with a clone of VM 9000', test: (c, h) => /resource\s+"proxmox_virtual_environment_vm"/.test(h.text(c)) && /clone\s*\{[^}]*vm_id\s*=\s*9000/.test(h.text(c)) },
          { id: 'sizing', label: 'Sets 2 cores and 4096 MB', test: (c, h) => /cores\s*=\s*2/.test(h.text(c)) && /dedicated\s*=\s*4096/.test(h.text(c)) },
          { id: 'notoken', label: 'No API token or password in the code; uses environment variables', test: (c, h) => !/^\s*(api_token|password)\s*=\s*"/m.test(h.text(c)) && /PROXMOX_VE_API_TOKEN/.test(h.text(c)) },
        ],
        sim: [textTurn(PVE_ANSWER, { input_tokens: 160, output_tokens: 700 })],
      },
    ],
  };

  /* =====================================================================
     Topic 5 — Drift detection and import
     ===================================================================== */
  const t5 = {
    id: 'w07-t5',
    title: 'Drift detection and bringing changes back into Terraform',
    programmeItem: 'Terraform on Azure and Proxmox · plan/apply and drift detection (free: HashiCorp docs)',
    blurb: 'Drift is any difference between your code and what is really running. Detect it on a schedule with plan -detailed-exitcode, then fix it by importing, updating the code, or reverting.',
    outcomes: [
      'Explain the three exit codes of terraform plan -detailed-exitcode',
      'Choose between import, updating code, and reverting for each drift',
      'Build a scheduled, plan-only drift job in GitHub Actions with Claude Code',
    ],
    concepts: [
      { t: 'What drift is', d: 'Changes made outside Terraform: portal edits, CLI hotfixes, other tools. The next apply either reverts them silently or fails.', ex: 'a tag added in the portal' },
      { t: '-detailed-exitcode', d: 'terraform plan returns 0 for no changes, 1 for an error, and 2 for a successful plan with changes. A scheduled job can alert on 2.', ex: 'terraform plan -detailed-exitcode' },
      { t: '-refresh-only', d: 'A plan mode that only updates state to match real infrastructure, without proposing changes to it. Useful to see what drifted.', ex: 'terraform plan -refresh-only' },
      { t: 'Import blocks', d: 'Since Terraform 1.5, an import block with to (the address) and id (the provider ID) brings an existing object into state during plan and apply, reviewed like any other change.', ex: 'import { to = ...  id = "/subscriptions/..." }' },
      { t: 'Generate config', d: 'With import blocks present, terraform plan -generate-config-out=file.tf can draft HCL for imported resources. Always review and tidy the output.', ex: 'terraform plan -generate-config-out=generated.tf' },
      { t: 'Fix, then prevent', d: 'Decide per drift: import it, change the code to match, or apply to revert. Then reduce portal write access so changes go through code.', ex: 'Reader in portal, Contributor for the pipeline' },
    ],
    leverage: [
      { t: 'Explain a drift report', d: 'Paste a refresh-only plan and ask Claude to group the drift by resource and suggest import, update code, or revert for each item.' },
      { t: 'Write import blocks', d: 'Give Claude the resource IDs from the portal or az CLI and ask for import blocks plus resource code that should produce an empty plan.' },
      { t: 'Build the drift job', d: 'Ask Claude Code for a scheduled GitHub Actions workflow that plans only, uses OIDC, and opens an issue when the exit code is 2.' },
    ],
    sources: [SRC.plan, SRC.importBlock, SRC.importCmd, SRC.drift, SRC.ccGha],
    quiz: [
      { q: 'terraform plan -detailed-exitcode returns 2. What does it mean?', options: ['The plan failed', 'The plan succeeded and there are changes (drift or pending code changes)', 'No changes'], a: 1, why: '0 = no changes, 1 = error, 2 = succeeded with changes.' },
      { q: 'Which is the safest default for a scheduled drift job?', options: ['terraform apply -auto-approve', 'Plan only, and alert a human on exit code 2', 'Delete drifted resources'], a: 1, why: 'Someone must decide whether to import, update code or revert; an automatic apply could undo an emergency fix.' },
    ],
    steps: [
      {
        id: 'w07-t5-s1', kind: 'guide', title: 'Claude Code: create drift on purpose, then detect and fix it', minutes: 40, source: SRC.drift,
        scenario: 'Use the sandbox stack from topic 3. Make a change in the portal, detect it with Terraform, then fix it with Claude Code.',
        task: [
          'In the portal, add a tag to the sandbox VNet and create one extra subnet by hand.',
          'Run <code>terraform plan -refresh-only</code> and <code>terraform plan -detailed-exitcode; echo $?</code> and note the exit code.',
          'Run prompts 1 and 2 in Claude Code, apply the fix in the sandbox, and confirm the exit code is now 0.',
        ],
        prompts: [
          { label: 'Explain the drift', where: 'Claude Code', text: 'Run terraform plan -refresh-only and terraform plan in this repo (do not apply). Explain each difference between the code and Azure, and for each one recommend import, update code, or revert, with a reason. Then show me the exit code of terraform plan -detailed-exitcode and what it means.' },
          { label: 'Fix it in code', where: 'Claude Code', text: 'Bring the hand-made subnet under Terraform with an import block (look up its resource ID with az CLI) and add the matching resource to the network module. Add the portal tag to the code. Run terraform plan and show me the result; the only actions should be the import and no destroys. Do not run apply.' },
        ],
        expected: ['An exit code of 2 before the fix and 0 after it', 'An import block for the subnet and matching module code', 'A plan with 1 to import and 0 to destroy'],
        verify: 'Check the import block syntax on the HashiCorp import page and the subnet resource arguments on the azurerm Registry page.',
        atWork: 'Portal hotfixes will happen during incidents. A routine of detect, explain and import with Claude Code turns them into reviewed code the same week.',
        checks: [
          { id: 'detect', label: 'I saw exit code 2 from -detailed-exitcode after the portal change', manual: true },
          { id: 'import', label: 'I imported the subnet and updated the code with no destroys', manual: true },
          { id: 'clean', label: 'The final plan exit code was 0', manual: true },
        ],
      },
    ],
  };

  /* =====================================================================
     Topic 6 — Apply
     ===================================================================== */
  const t6 = {
    id: 'w07-t6',
    title: 'Apply: bring a portal change back into Terraform, and add a drift check',
    programmeItem: 'Apply task · Bring one manual cloud-portal change back into Terraform. Add a drift check that would have caught it.',
    blurb: 'Take one real change someone made in the portal, bring it under Terraform with an import block, and add a scheduled drift check so the next one is caught the same day.',
    outcomes: [
      'Import a real portal-made resource with an import block and matching code',
      'Update code for attribute drift (such as tags) that needs no import',
      'Run a scheduled, plan-only drift check in GitHub Actions',
    ],
    concepts: [
      { t: 'Find a real change', d: 'Look in the Activity log or ask the team for a recent portal or CLI hotfix: an NSG rule, a tag, an app setting, a scale change.', ex: 'Activity log: Create or Update Security Rule' },
      { t: 'Import vs update', d: 'A new object needs an import block and a resource. A changed attribute on an existing resource only needs the code updated (or reverted).', ex: 'new rule = import · new tag = update code' },
      { t: 'Empty plan is the goal', d: 'After import and code changes, terraform plan should show only the import and no other changes. Anything else means the code does not match.', ex: 'Plan: 1 to import, 0 to add, 0 to change, 0 to destroy' },
      { t: 'Plan-only drift job', d: 'A scheduled workflow runs plan -detailed-exitcode and alerts on 2. It never applies by itself.', ex: "cron: '0 6 * * 1-5'" },
    ],
    leverage: [
      { t: 'Claude writes the import', d: 'Give Claude Code the change record and the resource ID; it writes the import block and resource and runs plan until it is clean.' },
      { t: 'Claude writes the workflow', d: 'Ask for the drift workflow with OIDC login and issue creation, then review permissions and triggers yourself.' },
      { t: 'Evidence for review', d: 'Ask Claude to summarize the before and after plans and the workflow run into a short note for the change record.' },
    ],
    sources: [SRC.importBlock, SRC.plan, SRC.nsg, SRC.ccGha],
    quiz: [
      { q: 'Someone added a tag to an existing NSG in the portal. What does Terraform need?', options: ['An import block', 'The tag added to the NSG resource in code (or reverted by apply)', 'A new resource'], a: 1, why: 'The NSG is already in state; only its attributes differ.' },
      { q: 'An NSG is managed with separate azurerm_network_security_rule resources. Should you add the new rule as an inline security_rule block?', options: ['Yes, it is shorter', 'No, mixing inline rules and separate rule resources makes them conflict', 'It does not matter'], a: 1, why: 'Use one style per NSG, otherwise each plan tries to undo the other.' },
    ],
    steps: [
      {
        id: 'w07-t6-s1', title: 'Import a portal-made NSG rule and add a drift check', minutes: 12, source: SRC.importBlock, files: ['W07_PORTAL_CHANGE'],
        scenario: 'During an incident, an engineer added an NSG rule and a tag in the portal. Ask Claude to bring both back into Terraform and to write the drift workflow that would have caught them.',
        task: ['Read <code>chg-5521-portal-change.txt</code>.', 'Click <b>Run</b>.', 'Check the import block, the rule resource, the tag, and that the workflow only plans and alerts on exit code 2.'],
        atWork: 'This is the pattern for every portal hotfix: import block, matching code, clean plan, and a drift job that raises it the next morning.',
        hint: 'An import block needs <code>to</code> (the resource address) and <code>id</code> (the Azure resource ID of the security rule).',
        body: {
          max_tokens: 16000, thinking: ADAPTIVE, output_config: { effort: 'high' },
          system: 'You are a senior platform engineer who owns the Terraform for a production Azure estate. Changes go through PRs; automation never applies without a human.',
          messages: user(L('<change_record>', '{{W07_PORTAL_CHANGE}}', '</change_record>', 'Bring both portal changes back into Terraform: write the import block and resource code for the new rule, and handle the tag. Say how to verify with plan. Then write a scheduled GitHub Actions workflow that would have caught this drift.')),
        },
        checks: [
          { id: 'import', label: 'Writes an import block with to = and id =', test: (c, h) => /import\s*\{[\s\S]*?to\s*=\s*azurerm_network_security_rule\.[\w-]+[\s\S]*?id\s*=\s*"[^"]+"[\s\S]*?\}/.test(h.text(c)) },
          { id: 'id', label: 'The id is the full security rule resource ID', test: (c, h) => /id\s*=\s*"\/subscriptions\/8f1c2d3e-0000-4000-8000-000000000001\/resourceGroups\/rg-shop-prod\/providers\/Microsoft\.Network\/networkSecurityGroups\/nsg-web\/securityRules\/allow-vendor-8443"/.test(h.text(c)) },
          { id: 'rule', label: 'Adds a matching azurerm_network_security_rule for port 8443 from 203.0.113.0/24', test: (c, h) => /resource\s+"azurerm_network_security_rule"/.test(h.text(c)) && /destination_port_range\s*=\s*"8443"/.test(h.text(c)) && /203\.0\.113\.0\/24/.test(h.text(c)) && /priority\s*=\s*310/.test(h.text(c)) },
          { id: 'tag', label: 'Handles the owner=vendor-ops tag in code', test: (c, h) => /owner\s*=\s*"vendor-ops"/.test(h.text(c)) },
          { id: 'drift', label: 'Workflow runs on a schedule with plan -detailed-exitcode and handles exit code 2', test: (c, h) => /schedule:/.test(h.text(c)) && /cron:/.test(h.text(c)) && /terraform plan[^\n]*-detailed-exitcode/.test(h.text(c)) && /'2'|== 2|-eq 2/.test(h.text(c)) },
          { id: 'noapply', label: 'The drift workflow never auto-applies', test: (c, h) => !/apply\s+-auto-approve/.test(h.text(c)) },
        ],
        sim: [{
          content: [
            think('New rule: import block with the full securityRules ID plus a separate azurerm_network_security_rule, since the NSG already uses separate rule resources. Tag: update the NSG tags in code, no import. Then a plan-only drift workflow with OIDC and -detailed-exitcode that opens an issue on exit code 2.'),
            { type: 'text', text: IMPORT_ANSWER },
          ],
          stop_reason: 'end_turn', usage: { input_tokens: 1100, output_tokens: 1500 },
        }],
      },
      {
        id: 'w07-t6-s2', kind: 'guide', title: 'Do it for real: one portal change, one drift job', minutes: 90, source: SRC.importBlock,
        scenario: 'Find one real manual change in your estate (Azure or Proxmox), bring it into Terraform through a normal PR, and put a drift job on that stack.',
        task: [
          'Find a real change in the Activity log or from the team. Record the change, who made it and when.',
          'Use prompts 1 and 2 in Claude Code in the real repo, on a branch. Open a PR; do not apply outside the pipeline.',
          'Merge the drift workflow, run it once manually, and keep the evidence listed below.',
        ],
        prompts: [
          { label: 'Find recent manual changes', where: 'Claude Code', text: 'Give me an az CLI command that lists write operations in the last 30 days on resource group [rg-name] from the Activity log, excluding our pipeline service principal [app-id], with time, caller, operation and resource ID. Then help me pick one change to bring into Terraform.' },
          { label: 'Import it on a branch', where: 'Claude Code', text: 'On a new branch, bring this resource into Terraform: [resource ID and short description]. Write an import block and the resource code in the right module, run terraform plan, and adjust until the plan shows only the import (no changes, no destroys). Do not run apply. Summarize the plan for my PR description. Remove any secrets from output.' },
          { label: 'Add the drift job', where: 'Claude Code', text: 'Add .github/workflows/terraform-drift.yml for this stack: weekday schedule plus manual trigger, OIDC login using our existing secrets, terraform plan -detailed-exitcode, fail on exit code 1, open or update a GitHub issue labelled drift on exit code 2. Plan only, never apply. Use least-privilege permissions.' },
        ],
        expected: ['A merged PR with the import block and code, with a plan showing only the import', 'A drift workflow that ran once and reported exit code 0 (or opened an issue for real drift)', 'A short note in the change record linking both'],
        verify: 'Compare the workflow permissions and OIDC settings with the GitHub and HashiCorp docs, and check that the pipeline identity for the drift job only needs read access.',
        atWork: 'Run this every time someone fixes production by hand. The drift job means you find out the next morning, not at the next apply.',
        checks: [
          { id: 'real', label: 'I imported one real manual change through a reviewed PR', manual: true },
          { id: 'plan', label: 'The PR plan showed only the import, with no destroys', manual: true },
          { id: 'job', label: 'The drift workflow is merged and ran at least once', manual: true },
          { id: 'note', label: 'I linked the PR and the workflow run in the change record', manual: true },
        ],
      },
    ],
  };

  PL.addWeek({
    week: 7,
    title: 'Infrastructure as code: Bicep, VMs, Terraform and drift',
    stream: 'role',
    hours: 9,
    focus: 'AZ-104 compute part 1 (ARM/Bicep and virtual machines), then Terraform on Azure and Proxmox: remote state, modules, plan review, and drift detection with Claude Code doing the heavy lifting.',
    apply: 'Bring one manual cloud-portal change back into Terraform. Add a drift check that would have caught it.',
    topics: [t1, t2, t3, t4, t5, t6],
  });
})();
